In [1]:
import numpy as np


In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
b.ndim

2

In [7]:
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [10]:
a.dtype

dtype('int64')

In [11]:
a.itemsize

8

In [13]:
a.size

3

In [14]:
a.nbytes

24

In [15]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [16]:
a[1,5]

np.int64(13)

In [17]:
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
a[:,2]

array([ 3, 10])

In [19]:
a[0,1:6:2]

array([2, 4, 6])

In [21]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [22]:
#3D example
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(b)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [24]:
b[0,1,1]

np.int64(4)

In [25]:
b[:,1,:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [26]:
b[:,:,1]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [29]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [31]:
np.full((4,5),56)

array([[56, 56, 56, 56, 56],
       [56, 56, 56, 56, 56],
       [56, 56, 56, 56, 56],
       [56, 56, 56, 56, 56]])

In [33]:
np.random.rand(4,2,3)

array([[[0.59355325, 0.92623437, 0.23711915],
        [0.44775964, 0.56961209, 0.69380535]],

       [[0.50183886, 0.23305232, 0.95512376],
        [0.13492187, 0.39398364, 0.90628483]],

       [[0.44914053, 0.07075304, 0.26056786],
        [0.71103561, 0.17925954, 0.0994089 ]],

       [[0.20177314, 0.31058987, 0.57053819],
        [0.65912785, 0.50885621, 0.96690694]]])

In [36]:
np.random.randint(7,size=(3,3))

array([[5, 3, 0],
       [3, 6, 5],
       [6, 3, 4]], dtype=int32)

In [37]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [48]:
a=np.ones((5,5))
print(a)
z=np.zeros((3,3))
z[1,1]=9
print(z)
a[1:4,1:4]=z
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [50]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [51]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])